Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"

  config.vm.network "private_network", ip: "192.168.33.10"

  # ssh settings
  # config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

end
