- name: check if '{{ package.name }}' is installed
  command: which '{{ package.name }}'
  changed_when: false
  failed_when: false
  register: package_installed


- name: download '{{ package.name }}' installer script
  get_url:
    url='{{ package.url }}'
    dest='/tmp/{{ package.name }}-installer'
    mode=0777
  when: package_installed | failed


- name: install '{{ package.name }}'
  command: /bin/bash '/tmp/{{ package.name }}-installer'
  when: package_installed | failed
