#!/usr/bin/env ansible-playbook

---
- hosts: all

  become_user: ubuntu
  become: yes
  connection: local


  tasks:

  - name: show all host variables
    debug: var=hostvars


  - name: whoami
    command: whoami
    register: whoami

  - set_fact: user={{ whoami.stdout }}

  - debug: var=whoami
  - debug: var=whoami.stdout
  - debug: var=user
